<a href="https://colab.research.google.com/github/Femmiwdy/DataMiningPreprocessing/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/Dataset.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:,-1].values

In [4]:
print(X)

[['Turki' 40.0 72000.0]
 ['Prancis' 27.0 50000.0]
 ['Arab' 35.0 55000.0]
 ['Singapura' 40.0 63000.0]
 ['Malaysia' 46.0 nan]
 ['Indonesia' 35.0 60000.0]
 ['Jepang' nan 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Arab' nan 85000.0]
 ['Singapura' 38.0 68000.0]]


In [5]:
print(Y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [7]:
print(X)

[['Turki' 40.0 72000.0]
 ['Prancis' 27.0 50000.0]
 ['Arab' 35.0 55000.0]
 ['Singapura' 40.0 63000.0]
 ['Malaysia' 46.0 64888.88888888889]
 ['Indonesia' 35.0 60000.0]
 ['Jepang' 38.625 52000.0]
 ['Indonesia' 48.0 79000.0]
 ['Arab' 38.625 85000.0]
 ['Singapura' 38.0 68000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 50000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 63000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 46.0 64888.88888888889]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 60000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.625 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.625 85000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 68000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [11]:
print(Y)

[1 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)


In [13]:
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.625 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 46.0 64888.88888888889]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 63000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 50000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.625 85000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 60000.0]]


In [14]:
print(X_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 68000.0]]


In [15]:
print(Y_train)

[0 1 1 0 1 1 0 1]


In [16]:
print(Y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [18]:
print(X_train)

[[0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.08792018887394243 -1.1912524548613261]
 [0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.132618903729023 -0.07347462057284189]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  2.6457513110645903 0.13963794703508503 0.5432303914483906]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 2.6457513110645903
  -0.3779644730092272 0.13963794703508503 -0.23728688939098194]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 -0.3779644730092272
  -0.3779644730092272 -2.0118207924684475 -1.3647007394922979]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.463612555960336 1.1502993876567915]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.08792018887394243 1.6706442415497065]
 [0.0 1.0 0.0 -0.3779644730092272 -0.37796447300

In [20]:
print(X_test)

[[1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.6878461835431967 -0.9310800279148687]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 2.6457513110645903
  -0.3779644730092272 -0.19135570519622766 0.19633382218644724]]


# New Section